//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTGD_ThuyetTrinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int IdSp { get; set; }
        public string Image { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> Category { get; set; }
        public string NameSp { get; set; }
    }
}
